### ISSUE TITLE
Finding whether two images are different or not

### ISSUE THREAD

**Issue by shankhanil007** [CrewMates-Open-Source/EduHelp#10]
One needs to figure out a way to determine whether two images ( of same dimensions and file format ) are different or not. You can display the %difference between the two images as a measure to determine this.

The purpose we want to achieve is that our screen recorder will continuously capture the lecture slides displayed in the selected area. But it should save only the unique screenshots and discard the repeating ones.

This is an open issue and anyone can contribute their ideas. Make a PR with your code implementation in a "Image Difference" Folder of the repository.

**Comment by AasthaRS** [comment]
We can check size of images and channels of both images by getting pixel value difference of both the images.
@shankhanil007 please assign this issue to me as a part of gssoc'21.
I want to work on it.

**Comment by shankhanil007** [comment]
@AasthaRS go ahead

**Comment by gaulghost** [comment]
I think we should convert the image into hsv format then analyse the pixels of bith the images. if the pixel in the one image is a 95% match with the pixel in another image, we shall pass it. So making a list of different valued pixel will tell if both images are same or not.

**Comment by gaulghost** [comment]
I also want to ask if there are two images both are same, difference is only that a filter is applied to one image then shall those images be considered same or different.

**Comment by GrayFlash** [comment]
The purspose behind this comparision between two images is that we are going to screenshot of your desktop screen while you are attending your meet, and we wish to save a screen shot only when the slide being presented in the meeting changes, So it will be great if you think accordingly.

For this issue you need to avoid changing fomat of image and consider that there are 3 channels in both images for RGB and you have to just compare and see by how much these two images vary.

**Comment by GrayFlash** [comment]
> if the pixel in the one image is a 95% match with the pixel in another image,

I am afraid for our requirement this may not suffice, consider two images of two slides of a ppt on your desktop, most of the pixels are going to remain the same as only the region where presentation goes on will change and that too the presentation template mostly remains same, i.e., the same background of slides. So it will be better to hardcode a bit higher threshold.

**Comment by yashasvimatta** [comment]
this can be done using structural similarity index. Can i work on this issue?

**Comment by GrayFlash** [comment]
@yashasvimatta please go ahead with it.

**Comment by GrayFlash** [comment]
@AasthaRS @gaulghost what is your status?? If you are stuck somewhere please discuss it here or in the discord channel.

**Comment by gaulghost** [comment]
@GrayFlash I made the project in colab to identify the changes by contour menthod but it is also detecting some part of image which is same, I am trying to find a way so that I can eliminate that
Original Image
![image](https://user-images.githubusercontent.com/49186033/111779540-44008700-88dc-11eb-944a-e89372b2ae48.png)
Changed Image
![image](https://user-images.githubusercontent.com/49186033/111779582-524ea300-88dc-11eb-9548-c77b3ffe444b.png)
Difference in contours
![image](https://user-images.githubusercontent.com/49186033/111779649-62ff1900-88dc-11eb-87cb-75e318114fd2.png)

In the above Image I have removed some extra contours (See the difference in Contours Image and Changed Image) by specifing width and height of contour but still I am not getting how to perfect it and detect it properly.
One easy way would be counting the number of contours present of specific width and height and if their number is higher than that specified by you... It will tell the change in slides. Drawback would be such as if there is a slide with only one or two words changed it might not detect it.

**Comment by GrayFlash** [comment]
@gaulghost I see you are going great, and your work will be a potential up-gradation on how we did this, it will be great if you can make a folder in our repo ```Jupyter_Notebooks``` and add your notebook there, keep the file name as (your work_(GithubId)).ipynb.
Make a PR, I will merge it and it will be great if @shankhanil007 and you can have a discussion on it, cause he worked on this earlier. Any other mentor @D3ADSH0T25 and @Apurva-tech are also welcome to participate in this issue.

**Comment by GrayFlash** [comment]
@gaulghost @shankhanil007 @Apurva-tech @D3ADSH0T25 please discuss here #28.
