### ISSUE TITLE
Faq section

### ISSUE THREAD

**Issue by arpit456jain** [CrewMates-Open-Source/EduHelp#69]
I think there must be a faq section at last of index.html
above footer because there is not much information  about website and project so user may have some general question 
an faq section also provide website a dynamic look
You can add suitable question and answer as per your website for it i can make a section for that

**Comment by arpit456jain** [comment]
I had already opened a PR kindly review it and assign this to me if you think its needed

**Comment by shankhanil007** [comment]
I will assign level2 or level3 tag to this issue based on your PR

**Comment by shankhanil007** [comment]
For a FAQ section, you would need content in the form of questions and answers, right? Do you have plans for how you will get the content? 
Since the importance of the website will be only after we have developed the core application of our project, I don't want to focus on giving you such content presently. If you find FAQ content will be more tedious, I would suggest changing it to "About Us" section and try improving it.

**Comment by arpit456jain** [comment]
> For a FAQ section, you would need content in the form of questions and answers, right? Do you have plans for how you will get the content?
> Since the importance of the website will be only after we have developed the core application of our project, I don't want to focus on giving you such content presently. If you find FAQ content will be more tedious, I would suggest changing it to "About Us" section and try improving it.

1. I can add a faq section with dummy text some one will suerly raised the issue for the content or you can insert the content later . the faq section will look like this.

https://user-images.githubusercontent.com/55352601/115187683-5e0ece80-a101-11eb-9744-25aa69381c4e.mp4


2. or I can work on it later  after you  developed the core application of your project

**Comment by shankhanil007** [comment]
Yeah you can work on it later. But I can tell you now by when we will be completing all the core functionalitites.
